# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Nuno Martins
#Title: 
email: nunomblm.1997@gmail.com
website: https://nmblm.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: 
github_username:  nmblm
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: nmblm
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Nuno and I'm an aspiring Game Developer.

  I am most skilled in: <mark>Unity</mark>, <mark>java</mark> and <mark>Throwing Games</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hybrid a coop Game
        link: https://web.tecnico.ulisboa.pt/ist193985/MDJMOJO/
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fas fa-shoe-prints
            url: https://web.tecnico.ulisboa.pt/ist193985/MDJMOJO/
        quote: >
          Project for Game Development Methodology course. First project I did in unity with a group of 3 other programmers.
        description: | # this will include new lines to allow paragraphs
          The course asked us to apply our knowledge to make a game. We decided to make a cooperative assymetrical game where one player is a thief and moves around the map and the other is a hacker that guides the player through the map.
      - layout: top-middle
        title: CyberNoodles
        link: https://github.com/NMBLM/CGJ_Dir
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fab fa-github
            url: https://github.com/NMBLM/CGJ_Dir
        quote: >
          Project for the course Computer Graphics for Games. 
        description: | # this will include new lines to allow paragraphs
          In this course we learnt about game engine software development. From rendering to character animation and physics. In this project we developed a version of a game engine with open-gl with our own math library. We implemented Bloom and SSAO(Screen space ambient occlusion). They are Cyber Noodles because in the beginning we wanted to created a cyberpunk noodle shop.
          
          ![cybernoodles](/images/cybernoodles.jpg "Cybernoodles")
          
      - layout: top-middle
        title: I Gotchu Fam!
        link: https://globalgamejam.org/2019/games/i-gotchu-fam
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fas fa-globe-europe
            url: https://globalgamejam.org/2019/games/i-gotchu-fam
        quote: >
          First time participating in a Game jam
        description: | # this will include new lines to allow paragraphs
          The theme for this game jam was "What home means to you". We created a top down 2D game developed in <bold>Unity</bold> where the player goes around looking for his family while escaping ghosts of bad memories.
          
      - layout: top-middle
        title: Lost in the Snow
        link: https://globalgamejam.org/2021/games/lost-snow-6-0
        # link_text: Project Website
        additional_links:
          - title:  
            icon: fas fa-globe-europe
            url: https://globalgamejam.org/2021/games/lost-snow-6-0
        quote: >
          Game Jam Project during the COVID Times
        description: | # this will include new lines to allow paragraphs
          The theme for this game jam was "Lost & Found". We created a 2D platformer developed in <bold>Unity</bold> where the player could switch between an explorer or a penguin and the objective was for the player to guide the penguin home.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: INESC-ID
        link: inesc-id.pt
        # link_text: boringcompany.com
        sub_title: Student Researcher
        caption: October 2019 - January 2021
        quote: >
          Worked as part of my MSc Thesis
        description: | # this will include new lines to allow paragraphs
            Researched Procedural Content Generation applied to Cooperative Games
            Created a Procedural Level Generator using a Genetic Algorithm that generated levels for Geometry Friends.
            
      - layout: left
        title: CGI
        link: www.cgi.com
        # link_text: boringcompany.com
        sub_title: Software Development Intern 
        caption: February 2022 - 
        quote: >
            Worked as a software developer and devops
        description: | # this will include new lines to allow paragraphs
            Worked on a lot of different areas including creating microservices using Spring Boot, Jenkins pipelines, deployments for Kubernetes and Openshift Clusters.
            Using many different tools such as Elasticsearch, Kafka, Prometheus, Grafana. Used GIT and agile methodology during development.
            

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Instituto Superior Técnico
        caption: 2015 - 2018
        sub_title: BSc Information Systems and Computer Engineering
        quote: >
          Técnico is the largest school of Architecture, Engineering, Science and Technology in Portugal, involving a community of over 10,000 people.
        description: | # this will include new lines to allow paragraphs
          During my time at Técnico I experienced many different hardships such as tight or overlapping deadlines. But it gave me the experience of working with many different people as part of a team and a base knowledge to understand and work in any of the areas related to computer science and engineering.

      - layout: left
        title: Instituto Superior Técnico
        caption: 2018 - 2021
        sub_title: MSc Information Systems and Computer Engineering
        quote: >
          Técnico is the largest school of Architecture, Engineering, Science and Technology in Portugal, involving a community of over 10,000 people.
        description: | # this will include new lines to allow paragraphs
          Continued studying in this masters to focus on fields of my own interest. I chose to focus on Artificial Intelligence, Game Development and Game Design. Writing a the thesis taught me skills related to academic research. 


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in programming and game development I also enjoy:
      - Gaming
      - Reading (webtoons and mangas mostly)

      This was me participating in MOJO our University's way to showcase student Game related projects:
      
      ![MOJO](/images/mojo.jpg "MOJO")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
